version: '3'

services:
  api:
    image: memotoro/api-db-rs
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_HOST=db

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
